export const mockSliders = [
  {
    _id: '1',
    titleEn: 'The Capital of Medical Businesses',
    titleAr: 'عاصمة الأعمال الطبية',
    subtitleEn: 'Premium medical office spaces in the heart of Baghdad',
    subtitleAr: 'مساحات مكتبية طبية فاخرة في قلب بغداد',
    imageUrl: '/images/slider1.jpg',
    order: 1,
    active: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: '2',
    titleEn: 'MedWorx Academy',
    titleAr: 'أكاديمية ميدووركس',
    subtitleEn: 'Continuous medical education & professional training',
    subtitleAr: 'التعليم الطبي المستمر والتدريب المهني',
    imageUrl: '/images/slider2.jpg',
    order: 2,
    active: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: '3',
    titleEn: 'Meeting & Conference Rooms',
    titleAr: 'قاعات الاجتماعات والمؤتمرات',
    subtitleEn: 'State-of-the-art facilities for medical conferences',
    subtitleAr: 'مرافق حديثة للمؤتمرات الطبية',
    imageUrl: '/images/slider3.jpg',
    order: 3,
    active: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const mockBlogs = [
  {
    _id: '1',
    titleEn: 'Why Baghdad Needs a Medical Business Hub',
    titleAr: 'لماذا تحتاج بغداد إلى مركز أعمال طبي',
    slug: 'why-baghdad-needs-medical-business-hub',
    contentEn: 'Baghdad\'s healthcare sector is growing rapidly. MedWorx provides the infrastructure that medical professionals need to establish and grow their practices in a modern, professional environment. Located in Al Harthya on Kindi Street, MedWorx occupies the 5th and 6th floors of a premium building, offering state-of-the-art facilities.',
    contentAr: 'ينمو قطاع الرعاية الصحية في بغداد بسرعة. يوفر ميدووركس البنية التحتية التي يحتاجها المتخصصون الطبيون لإنشاء وتنمية ممارساتهم في بيئة حديثة ومهنية.',
    imageUrl: '/images/blog1.jpg',
    tags: ['healthcare', 'baghdad', 'business'],
    published: true,
    createdAt: new Date('2026-03-15').toISOString(),
    updatedAt: new Date('2026-03-15').toISOString(),
  },
  {
    _id: '2',
    titleEn: 'MedWorx Academy: Elevating Medical Education',
    titleAr: 'أكاديمية ميدووركس: الارتقاء بالتعليم الطبي',
    slug: 'medworx-academy-elevating-medical-education',
    contentEn: 'MedWorx Academy (@medworx.academy) offers comprehensive training programs for medical professionals. From continuing medical education to specialized workshops, our academy is committed to raising the standard of healthcare practice in Iraq.',
    contentAr: 'تقدم أكاديمية ميدووركس برامج تدريبية شاملة للمتخصصين الطبيين. من التعليم الطبي المستمر إلى ورش العمل المتخصصة.',
    imageUrl: '/images/blog2.jpg',
    tags: ['academy', 'education', 'training'],
    published: true,
    createdAt: new Date('2026-03-20').toISOString(),
    updatedAt: new Date('2026-03-20').toISOString(),
  },
  {
    _id: '3',
    titleEn: 'Meeting Room Booking: A Complete Guide',
    titleAr: 'حجز قاعات الاجتماعات: دليل شامل',
    slug: 'meeting-room-booking-complete-guide',
    contentEn: 'MedWorx offers premium meeting and conference rooms equipped with the latest technology. Whether you need a space for a small team meeting or a large medical conference, our rooms can accommodate your needs with professional AV equipment and catering services.',
    contentAr: 'يقدم ميدووركس قاعات اجتماعات ومؤتمرات فاخرة مجهزة بأحدث التقنيات.',
    imageUrl: '/images/blog3.jpg',
    tags: ['meetings', 'booking', 'facilities'],
    published: true,
    createdAt: new Date('2026-04-01').toISOString(),
    updatedAt: new Date('2026-04-01').toISOString(),
  },
  {
    _id: '4',
    titleEn: 'Customer Service Excellence at MedWorx',
    titleAr: 'التميز في خدمة العملاء في ميدووركس',
    slug: 'customer-service-excellence',
    contentEn: 'At MedWorx, we believe exceptional customer service is the foundation of success. Our dedicated team (@medworx.cs) ensures that every tenant and visitor experiences the highest level of professionalism and care.',
    contentAr: 'في ميدووركس، نؤمن بأن خدمة العملاء الاستثنائية هي أساس النجاح.',
    imageUrl: '/images/blog4.jpg',
    tags: ['service', 'quality', 'support'],
    published: true,
    createdAt: new Date('2026-04-05').toISOString(),
    updatedAt: new Date('2026-04-05').toISOString(),
  },
];

export const mockRooms = [
  {
    _id: '1',
    nameEn: 'Al-Razi Conference Hall',
    nameAr: 'قاعة الرازي للمؤتمرات',
    capacity: 50,
    pricePerHour: 150000,
    currency: 'IQD',
    amenities: ['projector', 'whiteboard', 'video-conferencing', 'catering'],
    imageUrl: '/images/room1.jpg',
    active: true,
  },
  {
    _id: '2',
    nameEn: 'Ibn Sina Meeting Room',
    nameAr: 'غرفة اجتماعات ابن سينا',
    capacity: 20,
    pricePerHour: 75000,
    currency: 'IQD',
    amenities: ['projector', 'whiteboard', 'video-conferencing'],
    imageUrl: '/images/room2.jpg',
    active: true,
  },
  {
    _id: '3',
    nameEn: 'Al-Zahrawi Workshop Room',
    nameAr: 'غرفة ورشة الزهراوي',
    capacity: 30,
    pricePerHour: 100000,
    currency: 'IQD',
    amenities: ['projector', 'whiteboard', 'lab-equipment'],
    imageUrl: '/images/room3.jpg',
    active: true,
  },
  {
    _id: '4',
    nameEn: 'Executive Boardroom',
    nameAr: 'غرفة مجلس الإدارة',
    capacity: 12,
    pricePerHour: 100000,
    currency: 'IQD',
    amenities: ['projector', 'video-conferencing', 'premium-catering'],
    imageUrl: '/images/room4.jpg',
    active: true,
  },
];

export const mockBookings = [
  {
    _id: '1',
    room: mockRooms[0],
    guestName: 'Dr. Ahmad Hassan',
    guestEmail: 'ahmad@example.com',
    guestPhone: '+964 770 123 4567',
    date: new Date('2026-04-10').toISOString(),
    startTime: '09:00',
    endTime: '12:00',
    purpose: 'Medical Research Symposium',
    status: 'approved',
    createdAt: new Date('2026-04-06').toISOString(),
  },
  {
    _id: '2',
    room: mockRooms[1],
    guestName: 'Dr. Sara Ali',
    guestEmail: 'sara@example.com',
    guestPhone: '+964 770 987 6543',
    date: new Date('2026-04-12').toISOString(),
    startTime: '14:00',
    endTime: '16:00',
    purpose: 'Department Planning Meeting',
    status: 'pending',
    createdAt: new Date('2026-04-07').toISOString(),
  },
];

export const mockStats = {
  sliders: mockSliders.length,
  blogs: mockBlogs.length,
  rooms: mockRooms.length,
  bookings: mockBookings.length,
  pendingBookings: mockBookings.filter(b => b.status === 'pending').length,
  messages: 5,
  unreadMessages: 2,
};
